### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Amin52728** [Sileo/Sileo#130] opened 2021-04-08 06:36 UTC
Sileo crashed for memory limit on A8
I jailbreak with Odysseyra1n

Here is crash log:
https://mega.nz/file/IWhFwKxa#9kFy9P_iqrtGMM8Kzucra_8xo8bodBD_DsQDX3ObxaY

**Comment by captinc** [comment] 2021-04-08 19:33
Known issue, it is on the todo list, so closing for now. Due to how Sileo's backend is coded, I'm not sure how much can be done about it, but I have been keeping an eye out in case it's a simple fix. It only happens when you do a ton (50+) of separate installations in the same app session, so it's not a *huge* issue, but I will address it if reasonably possible.

**Closed by captinc** 2021-04-08 19:33 UTC

**Comment by elihwyma** [comment] 2021-04-08 19:39
Known issue, it is on the todo list, so closing for now. Due to how Sileo's backend is coded, I'm not sure how much can be done about it, but I have been keeping an eye out in case it's a simple fix. It only happens when you do a ton (50+) of separate installations in the same app session, so it's not a huge issue, but I will address it if reasonably possible.

**Comment by Amin52728** [comment] 2021-04-08 20:34
But this happens when i refresh the sources

**Comment by Amin52728** [comment] 2021-04-08 20:35
> Known issue, it is on the todo list, so closing for now. Due to how Sileo's backend is coded, I'm not sure how much can be done about it, but I have been keeping an eye out in case it's a simple fix. It only happens when you do a ton (50+) of separate installations in the same app session, so it's not a huge issue, but I will address it if reasonably possible.

But this happens when i refresh the sources

**Comment by Amin52728** [comment] 2021-04-08 20:54
> A simple source refresh immediately after launching Sileo causes a jetsam crash every single time?

Not exactly because the first refresh after launching Sileo is no problem, but it happens when I add a repo and want to refresh the sources.

https://mega.nz/file/sGpAhKyB#gRX77JYrAgN9kKR8ZO8nU126f3IR_y5FXm2iF-8CIRM

**Comment by captinc** [comment] 2021-04-08 20:57
How many repos do you have? How many tweaks? How often? Can it be reliably reproduced? Keep in mind that you have a really old device with very little RAM to begin with

**Comment by Amin52728** [comment] 2021-04-08 21:09
> How many repos do you have? How many tweaks? How often? Can it be reliably reproduced? Keep in mind that you have a really old device with very little RAM to begin with

63 repos
17 tweaks
I know i have an old iPhone, but a year ago when i was on versions 12.2 or 12.3 and i was jailbroken with Chimera, i didn’t have such a problem.

**Comment by captinc** [comment] 2021-04-08 21:23
You definitely should not have 63 repos....

As said earlier, the issue currently only occurs in extreme cases. The root cause can be either a simple fix or a design flaw in Sileo's backend, but I have not yet determined which one. I hope it's a simple fix, but if not, it would require too large of a backend rewrite to be practical. I will keep an eye out.

**Comment by Amin52728** [comment] 2021-04-08 21:39
> You definitely should not have 63 repos....
> 
> 
> 
> As said earlier, the issue currently only occurs in extreme cases. The root cause can be either a simple fix or a design flaw in Sileo's backend, but I have not yet determined which one. I hope it's a simple fix, but if not, it would require too large of a backend rewrite to be practical. I will keep an eye out. 

Thanks for your hard working🤍
Keep it up
