### ISSUE TITLE
There is an issue with Sileo v2.4.2 not displaying installed plugins and classifications effectively on iOS 14.3

### ISSUE THREAD

**Issue by Szhann** [Sileo/Sileo#282] opened 2023-04-16 01:52 UTC
![Uploading 1C9B348D-2ADE-4D47-BE36-670148956993.p
![D1F78FB7-AF75-4FD3-8C23-54A38B186C7B](https://user-images.githubusercontent.com/22450827/232261900-c96d66eb-f6e4-47d5-b96c-aa68354a32c6.png)
ng…]()

**Comment by Szhann** [comment] 2023-04-16 01:54
![57251453-3CBD-42D2-95C4-DAB957B7CD86](https://user-images.githubusercontent.com/22450827/232261947-6a7bec34-3e26-4e12-b07b-f0b446ad741e.png)
![2C4F49D8-92FC-4B37-B078-B91DDCC62252](https://user-images.githubusercontent.com/22450827/232261949-9bffd5a3-995b-4b7d-a2b8-3774626c3fb7.png)

**Comment by Szhann** [comment] 2023-04-16 01:56
The above shows 9 installed categories, which will display a lot when entering this category. Clicking on all category labels will display the category title as installed

**Comment by elihwyma** [comment] 2023-04-16 16:59
Closing as duplicate of https://github.com/Sileo/Sileo/issues/280

**Closed by elihwyma** 2023-04-16 16:59 UTC
